# Generated by Django 4.1.5 on 2023-02-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VS', '0002_file_upload_delete_vsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload1',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
    ]
