# Generated by Django 4.1.5 on 2023-02-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VS', '0003_file_upload1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload1',
            old_name='file_name',
            new_name='file_names',
        ),
        migrations.RenameField(
            model_name='file_upload1',
            old_name='my_file',
            new_name='my_file1',
        ),
    ]
